# Generated by Django 4.0 on 2023-09-14 10:29

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_address_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.IntegerField(validators=[users.validators.max_value]),
        ),
    ]
