# Generated by Django 4.0 on 2023-09-09 11:10

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[blog.validators.max_len_validator]),
        ),
    ]
